import { Inter } from "next/font/google";
import "@/styles/globals.scss";
import Nav from "@/common/nav/Nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Skill On Application",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <div style={{ width: "90%" }}>{children}</div>
      </body>
    </html>
  );
}
